import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { entryOwnership, ownAfter, postMoney, proRata, stakeValue } from './ownership'
import type { RoundTerms } from './ownership'

/**
 * The engine is checked against `tools/oracle.py`, which implements the same
 * maths twice — once as the angel-side formula and once as an independent
 * share-count cap table — and asserts the two agree.
 *
 * The fixture is generated by `npm run oracle:emit`. CI regenerates it and fails
 * if it differs from what is committed, so the two implementations cannot drift
 * apart quietly.
 */

interface Fixture {
  seedRound: { preMoneyCents: number; raisedCents: number }
  seriesB: { preMoneyCents: number; raisedCents: number }
  seriesBPool: number
  entryCents: number
  A: { ownership: number; postMoneyCents: number }
  B: { ownership: number; valueCents: number; postMoneyCents: number }
  C: { proRataCents: number; ownership: number; valueCents: number }
  D: { ownership: number; proRataCents: number }
}

const fixture = JSON.parse(
  readFileSync(fileURLToPath(new URL('../../tools/golden-cases.json', import.meta.url)), 'utf8'),
) as Fixture

const terms = (r: { preMoneyCents: number; raisedCents: number }): RoundTerms => ({
  preMoney: r.preMoneyCents,
  raised: r.raisedCents,
})

const seed = terms(fixture.seedRound)
const seriesB = terms(fixture.seriesB)
const seriesBPooled: RoundTerms = { ...seriesB, newOptionPool: fixture.seriesBPool }
const PLACES = 12

describe('the engine agrees with the Python oracle', () => {
  it('A — entry ownership and post-money', () => {
    expect(entryOwnership(fixture.entryCents, seed)).toBeCloseTo(fixture.A.ownership, PLACES)
    expect(postMoney(seed)).toBe(fixture.A.postMoneyCents)
  })

  it('B — dilution from sitting out, and what the stake is then worth', () => {
    const after = ownAfter(fixture.A.ownership, seriesB)
    expect(after).toBeCloseTo(fixture.B.ownership, PLACES)
    expect(stakeValue(after, postMoney(seriesB))).toBe(fixture.B.valueCents)
    expect(postMoney(seriesB)).toBe(fixture.B.postMoneyCents)
  })

  it('C — the pro-rata cheque and the position it holds', () => {
    const cheque = proRata(fixture.A.ownership, seriesB)
    expect(cheque).toBe(fixture.C.proRataCents)
    const after = ownAfter(fixture.A.ownership, seriesB, cheque)
    expect(after).toBeCloseTo(fixture.C.ownership, PLACES)
    expect(stakeValue(after, postMoney(seriesB))).toBe(fixture.C.valueCents)
  })

  it('D — the same round once a new option pool is carved out', () => {
    expect(ownAfter(fixture.A.ownership, seriesBPooled)).toBeCloseTo(fixture.D.ownership, PLACES)
    expect(proRata(fixture.A.ownership, seriesBPooled)).toBe(fixture.D.proRataCents)
  })
})
