import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { entryOwnership, ownAfter, postMoney, proRata, stakeValue } from './ownership'
import type { RoundTerms } from './ownership'
import { exitProceeds } from './exit'
import { applyFees } from './fees'

/**
 * The engine is checked against `tools/oracle.py`, which implements the same
 * maths twice — once as the angel-side formula and once as an independent
 * share-count cap table — and asserts the two agree.
 *
 * The fixture is generated by `npm run oracle:emit`. CI regenerates it and fails
 * if it differs from what is committed, so the two implementations cannot drift
 * apart quietly.
 */

interface Fixture {
  seedRound: { preMoneyCents: number; raisedCents: number }
  seriesB: { preMoneyCents: number; raisedCents: number }
  seriesBPool: number
  entryCents: number
  A: { ownership: number; postMoneyCents: number }
  B: { ownership: number; valueCents: number; postMoneyCents: number }
  C: { proRataCents: number; ownership: number; valueCents: number }
  D: { ownership: number; proRataCents: number }
  I: {
    ownership: number
    exitCents: number
    totalRaisedCents: number
    proceedsCents: number
  }
  J: {
    chequeCents: number
    grossCents: number
    entryPercent: number
    carryPercent: number
    outlayCents: number
    carryCents: number
    netCents: number
    dragCents: number
    grossMultiple: number
    netMultiple: number
  }
  K: {
    exitCents: number
    totalRaisedCents: number
    investedCents: number
    proceedsCents: number
    naiveCents: number
  }
  feeDrag: {
    grossCents: number
    carryCents: number
    netCents: number
    outlayCents: number
    grossMultiple: number
    netMultiple: number
  }
}

const fixture = JSON.parse(
  readFileSync(fileURLToPath(new URL('../../tools/golden-cases.json', import.meta.url)), 'utf8'),
) as Fixture

const terms = (r: { preMoneyCents: number; raisedCents: number }): RoundTerms => ({
  preMoney: r.preMoneyCents,
  raised: r.raisedCents,
})

const seed = terms(fixture.seedRound)
const seriesB = terms(fixture.seriesB)
const seriesBPooled: RoundTerms = { ...seriesB, newOptionPool: fixture.seriesBPool }
const PLACES = 12

describe('the engine agrees with the Python oracle', () => {
  it('A — entry ownership and post-money', () => {
    expect(entryOwnership(fixture.entryCents, seed)).toBeCloseTo(fixture.A.ownership, PLACES)
    expect(postMoney(seed)).toBe(fixture.A.postMoneyCents)
  })

  it('B — dilution from sitting out, and what the stake is then worth', () => {
    const after = ownAfter(fixture.A.ownership, seriesB)
    expect(after).toBeCloseTo(fixture.B.ownership, PLACES)
    expect(stakeValue(after, postMoney(seriesB))).toBe(fixture.B.valueCents)
    expect(postMoney(seriesB)).toBe(fixture.B.postMoneyCents)
  })

  it('C — the pro-rata cheque and the position it holds', () => {
    const cheque = proRata(fixture.A.ownership, seriesB)
    expect(cheque).toBe(fixture.C.proRataCents)
    const after = ownAfter(fixture.A.ownership, seriesB, cheque)
    expect(after).toBeCloseTo(fixture.C.ownership, PLACES)
    expect(stakeValue(after, postMoney(seriesB))).toBe(fixture.C.valueCents)
  })

  it('D — the same round once a new option pool is carved out', () => {
    expect(ownAfter(fixture.A.ownership, seriesBPooled)).toBeCloseTo(fixture.D.ownership, PLACES)
    expect(proRata(fixture.A.ownership, seriesBPooled)).toBe(fixture.D.proRataCents)
  })

  it('I — a clean exit pays the ownership share', () => {
    const result = exitProceeds({
      valueCents: fixture.I.exitCents,
      totalRaisedCents: fixture.I.totalRaisedCents,
      ownership: fixture.I.ownership,
      investedCents: fixture.K.investedCents,
    })
    expect(result.regime).toBe('clean')
    expect(result.lowCents).toBe(fixture.I.proceedsCents)
  })

  it('J — fees on a $500k gross', () => {
    const result = applyFees(
      [{ chequeCents: fixture.J.chequeCents, entryFeeCents: fixture.J.chequeCents * fixture.J.entryPercent }],
      fixture.J.grossCents,
      { carry: { percent: fixture.J.carryPercent, basis: 'per_deal' } },
    )
    expect(result.outlayCents).toBe(fixture.J.outlayCents)
    expect(result.carryCents).toBe(fixture.J.carryCents)
    expect(result.netCents).toBe(fixture.J.netCents)
    expect(result.dragCents).toBe(fixture.J.dragCents)
    expect(result.grossMultiple).toBeCloseTo(fixture.J.grossMultiple, 9)
    expect(result.netMultiple).toBeCloseTo(fixture.J.netMultiple, 9)
  })

  it('K — a downside exit pays your share of the preference stack', () => {
    const result = exitProceeds({
      valueCents: fixture.K.exitCents,
      totalRaisedCents: fixture.K.totalRaisedCents,
      ownership: fixture.I.ownership,
      investedCents: fixture.K.investedCents,
    })
    expect(result.regime).toBe('downside')
    expect(result.lowCents).toBe(fixture.K.proceedsCents)
    expect(stakeValue(fixture.I.ownership, fixture.K.exitCents)).toBe(fixture.K.naiveCents)
  })

  it('reproduces the fee drag figure the plan illustrates', () => {
    const result = applyFees(
      [{ chequeCents: fixture.K.investedCents, entryFeeCents: fixture.K.investedCents * fixture.J.entryPercent }],
      fixture.feeDrag.grossCents,
      { carry: { percent: fixture.J.carryPercent, basis: 'per_deal' } },
    )
    expect(result.carryCents).toBe(fixture.feeDrag.carryCents)
    expect(result.netCents).toBe(fixture.feeDrag.netCents)
    expect(result.outlayCents).toBe(fixture.feeDrag.outlayCents)
    expect(result.grossMultiple).toBeCloseTo(fixture.feeDrag.grossMultiple, 9)
    expect(result.netMultiple).toBeCloseTo(fixture.feeDrag.netMultiple, 9)
  })
})
